name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 0
  DISTRO: fedora # Standard distribution
  DOCKER_FILE: packaging/docker/Dockerfile.${DISTRO}
  DOCKER_TAG: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE: registry.git.rwth-aachen.de/acs/public/villas/node
  DOCKER_IMAGE_DEV: ${DOCKER_IMAGE}/dev-${DISTRO}
  DOCKER_CLI_EXPERIMENTAL: enabled
  CMAKE_BUILD_OPTS: "--parallel 16"
  CMAKE_EXTRA_OPTS: "-DCMAKE_BUILD_TYPE=Release"
  CMAKE_EXTRA_OPTS_FEDORA_MINIMAL: >
    -DVILLAS_COMPILE_WARNING_AS_ERROR=ON
    -DWITH_API=OFF
    -DWITH_CLIENTS=OFF
    -DWITH_CONFIG=OFF
    -DWITH_DOC=OFF
    -DWITH_FPGA=OFF
    -DWITH_GRAPHVIZ=OFF
    -DWITH_HOOKS=OFF
    -DWITH_LUA=OFF
    -DWITH_OPENMP=OFF
    -DWITH_PLUGINS=OFF
    -DWITH_SRC=OFF
    -DWITH_TESTS=OFF
    -DWITH_TOOLS=OFF
    -DWITH_WEB=OFF
    -DCMAKE_MODULE_PATH=/usr/local/lib64/cmake
    -DCMAKE_PREFIX_PATH=/usr/local
  CACHIX_CACHE_NAME: villas

jobs:

  build:

    runs-on: ubuntu-latest
    containter: ghcr.io/${{ github.repository_owner }}/fedora
    permissions:
      contents: read
      packages: write
    name: "prepare:docker [${{ matrix.name }}]"
         
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup build directory cache
      uses: actions/cache@v5
      with:
        path: ${{ github.workspace }}/build
        key: build-fedora-dir-cache-${{ github.ref }}

    - name: Configure CMake
      shell: bash
      working-directory: ${{ github.workspace }}/build
      run: cmake -S . -B build ${CMAKE_OPTS} ${CMAKE_EXTRA_OPTS}
        
    - name: Build dpsimpy and test examples
      shell: bash
      working-directory: ${{ github.workspace }}/build
      run: cmake --build build ${CMAKE_BUILD_OPTS}

    - name: Archive build directory
      uses: actions/upload-artifact@v7
      with:
        path: ${{ github.workspace }}/build
        name: build-fedora-examples-cache-${{ github.sha }}
        retention-days: 1

    

    